# See example: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

name: Create PR from dev into master
on:
  push:
    branches:
      - development

jobs:
  sync-master:
    runs-on: ubuntu-latest
    checks: none # Prevents this from showing up in PR checklists
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: development
          title: "🌳🤖 - development 🠮 master"
          body: "Automated PR for merging changes in `development` to `master`, created by `sync-master` GitHub action"
