# Pulled from example: https://github.com/peter-evans/create-pull-request/blob/main/docs/examples.md#keep-a-branch-up-to-date-with-another

name: Create PR into master
on:
  push:
    branches:
      - development

jobs:
  syncMaster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Reset branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: master
          branch: development
          title: Automatic dev->master PR
          
